[package]
name = "abstract_chearmyp_source"
version = "0.3.0-dev"
authors = ["Kenneth Trecy Tobias <33564322+KennethTrecy@users.noreply.github.com>"]
edition = "2018"

[features]
default = []
no_std = []
str_source = []
slice_u8_source = []
vec_source_collection = []
